### ISSUE TITLE
[ui] 루트 뷰 / 루트 뷰 구현

### ISSUE THREAD

**Issue by CHANGEL1004** [DO-SOPT-APP6-NAVER-MAP/NAVER-MAP-AOS#5]
## 💡 ISSUE
루트 뷰 구현

## 📌 TO DO

task1 루트 뷰 레이아웃 상단 출발지 창/ 목적지 창 구현
task2 루트 뷰 레이아웃 서버 받아올 이미지 리사이클러 뷰에 더미 데이터 넣어서 테스트

**Comment by Sangwook123** [comment]
이슈에 TO DO 채워주세용
